name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  

      - name: Install tools
        run: |
         sudo apt-get update
         sudo apt-get install -y cmake
         sudo apt-get install -y clang
         sudo apt-get install -y ninja-build
      
      - name: Compile and install SDL
        run: |
          git clone https://github.com/libsdl-org/SDL.git --depth 1
          cmake -S SDL -B SDL/build -DCMAKE_GENERATOR=Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DSDL_TEST_LIBRARY=OFF
          cmake --build SDL/build
          sudo cmake --install SDL/build

      - name: Install Vulkan SDK
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.268-focal.list https://packages.lunarg.com/vulkan/1.3.268/lunarg-vulkan-1.3.268-focal.list
          sudo apt update
          sudo apt install vulkan-sdk

      - name: CMake Configure
        run: cmake --preset linux64-release

      - name: CMake Build
        shell: bash
        run: cmake --build build
