name: Ubuntu

on:   
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Install SDL2
        run: sudo apt install libsdl2-dev
        
      - name: Install GLM
        run: sudo apt install libglm-dev

      - name: Install Vulkan SDK
        run: wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.148-bionic.list https://packages.lunarg.com/vulkan/1.2.148/lunarg-vulkan-1.2.148-bionic.list && sudo apt update && sudo apt install vulkan-sdk  

      - name: CMake Configure
        run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: CMake Build
        shell: bash
        run: cmake --build build/ --config $BUILD_TYPE
