name: CMake

on:
  push:
    branches: [ master, windows-ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install SDL2
      run: git clone https://github.com/libsdl-org/SDL.git && cmake -S SDL -B SDL/build -DCMAKE_INSTALL_PREFIX=SDL/install && cmake --build SDL/build --config Release --target INSTALL
