name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - run: choco install cmake
      - run: choco install ninja
      - run: choco install llvm
      - run: choco install vulkan-sdk
      
      - uses: actions/checkout@v2

      - name: Compile and install SDL
        run: git clone https://github.com/libsdl-org/SDL.git && cmake -S SDL -B SDL/build -DSDL_TEST_LIBRARY=OFF && cmake --build SDL/build --config Release --target INSTALL
      
      - name: CMake Configure
        run: cmake --preset win64-release

      - name: CMake Build
        run: cmake --build build
